### ISSUE TITLE
Align messages depending on sender

### ISSUE THREAD

**Issue by MsPockets** [MsPockets/cohorts#3]
This should fix the problem with the messages all being on the same side of the screen.

Add a ternary operator to the class of each message box
`{message.displayName === currentUser.displayName ? 'my-message' : 'not-my-message'}`

Then add this to `global.css`
```css
.my-message {
  display: row-reverse;
}
```

That should do it!

**Comment by MsPockets** [comment]
I began working on this and got the desired sides my using this code 
`style.css`
```css
.my-message {
	float: right;
	clear: both;
}
```
`Chats.svelte`
```html
<div class="box chat-box" id="chat-box" bind:this={chatBox}>
    {#each messages.sort((a,b) => a.date - b.date) as {message, uid, displayName}}

      <div class="notification {uid === currentUser.uid ? 'my-message' : 'not-my-message'}">
        <div class="sender">
        {displayName}:
      </div> 
      <div class="message-content">
        {@html marked(message)}
      </div>
      </div>
    {/each}
  </div>
```

Somehow the ordering of the messages got messed up and they will either display on the correct side but out of order, or they will display on the correct side, but without proper spacing inbetween (a message from 2 different users can be on the same 'line' but on the correct side of the chatbox

**Comment by MsPockets** [comment]
for sake of readability, I changed 'my-message' and 'not-my-message' to 'rgt' and 'lft' respectively

`Chats.svelte`
```html
<div class="box chat-box" id="chat-box" bind:this={chatBox}>
    {#each messages.sort((a,b) => a.date - b.date) as {message, uid, displayName}}

      <div class="notification {uid === currentUser.uid ? 'rgt' : 'lft'}">
        <div class="sender">
        {displayName}:
      </div> 
      <div class="message-content">
        {@html marked(message)}
      </div>
      </div>
    {/each}
  </div>
``` 

`global.css`
```css
.rgt {
	float: right;
	position: relative;
	clear: both;
}
.lft {
	float: left;
	position: relative;
	clear: both;
}
```
This seems to have solved the issue!
